apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: campaign-express-staging

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

commonLabels:
  environment: staging
